### ISSUE TITLE
Change break migrations

### ISSUE THREAD

**Issue by tboulogne** [sonus21/error-tracker#16]
Hello,

the change 
```
dependencies = [
        ('django', '0001_initial'),
    ]
to
 dependencies = [
        ('error_tracker', '0001_initial'),
    ]
```
made migrations broken.

The error message

>django.db.migrations.exceptions.NodeNotFoundError: Migration django.0002_auto_20201018_1311 dependencies reference nonexistent parent node ('error_tracker', '0001_initial')

Regards

**Comment by sonus21** [comment]
Can you please let me know how are you running this code? For me it's working fine.
