### ISSUE TITLE
UserWarning: APP_ERROR_DB_MODEL is not set using default model

### ISSUE THREAD

**Issue by magalysuchecki** [sonus21/error-tracker#23]
/error_tracker/django/__init__.py:28: UserWarning: APP_ERROR_DB_MODEL is not set using default model
  warnings.warn("APP_ERROR_DB_MODEL is not set using default model")
/error_tracker/libs/utils.py:121: UserWarning: Default Masking module will be used
  warnings.warn(message)
/error_tracker/libs/utils.py:121: UserWarning: Default Notification module will be used
  warnings.warn(message)
/error_tracker/libs/utils.py:121: UserWarning: Default ContextBuilder module will be used 
warnings.warn(message)

**Comment by sonus21** [comment]
These are just warning no harm in that.
