### ISSUE TITLE
All variables in traceback are `None`

### ISSUE THREAD

**Issue by yetem** [sonus21/error-tracker#26]
I used the 3.0.0 version of error -tracker for Django 4.2.1 for some time. In my admin in all traceback, I see `None` instead of the actual value of variables. 

I searched in the documentation but don't see anything about It. I don't have any masking variables set.

![Zrzut ekranu 2023-07-16 o 12 50 48](https://github.com/sonus21/error-tracker/assets/12342128/844ab98e-ecbf-4ea1-9ddf-5823db6a3fff)

**Comment by sonus21** [comment]
is it happening always or occassionly ?

**Comment by yetem** [comment]
Always, in both projects where I used it.

**Comment by sonus21** [comment]
I see, this was a bug try latest version 3.1.0

**Comment by yetem** [comment]
It fixed now, thank you!
