### ISSUE TITLE
Reduce dependencies?

### ISSUE THREAD

**Issue by matthijskooijman** [sonus21/error-tracker#9]
Currently, this package depends on Flask, Django and Django-rest-framework, but is that really needed? Typically, when this library is used with django and/or django-rest-framework or Flask, then the application will already depend on those packages and error-tracker could just import them.

Typically an application will not use both Flask and Django at the same time, so this installs a bunch of packages that are never used.

Maybe the dependencies can be made optional using setup.py's "extra" feature, or just removed altogether (with the responsibility for installing these moved to the application). The latter might need some changes in the code (haven't checked) to ensure things are only imported when actually needed and/or to have a graceful fallback if imports are not available.

**Comment by sonus21** [comment]
Thanks Matthijs
Your idea looks to be good to me, I have changed code to use new dependency model. Can you please try to pull the latest code from dev branch and let me know if you find any issue with that?

**Comment by matthijskooijman** [comment]
I had a quick look at the code, looks good to me. One further suggestion: Maybe separate the django and django-rest-framework dependencies into separate extras? e.g. in my project I'm just django, but not d-r-f, so that would be pulled in unnecessarily. The same might hold for Flask and SQL-alchemy, but I'm not familiar enough with those to tell.

As for trying the branch, I have not actually started using this app in my project (I was missing some things, so I just fell back to the default django error e-mailer) and I'm short on time, so I can't easily test right now.

**Comment by sonus21** [comment]
For flask SQL-Alchemy is required since database connection depends on that unless you provide your own wrapper of model. For DRF i can make another extra dependency.
